this is a #ball.

In [1]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

In [4]:
#stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

we are studying nlp and this is the first lecture. we have completed supervised and unsupervised learning.

In [5]:
text = "we are studying nlp and this is the first lecture."

In [6]:
from nltk.tokenize import word_tokenize

tokens = word_tokenize(text)

In [8]:
tokens_without_stopwords = [word for word in tokens if word not in stopwords]

In [10]:
tokens_without_stopwords

['studying', 'nlp', 'first', 'lecture', '.']

In [11]:
tokens_without_punctuation = [word for word in tokens_without_stopwords if word.isalnum()]

In [12]:
tokens_without_punctuation

['studying', 'nlp', 'first', 'lecture']

In [13]:
#stemming and lemmitization
from nltk.stem import PorterStemmer

p = PorterStemmer()

stemed_tokens = [p.stem(word) for word in tokens_without_punctuation]



In [14]:
stemed_tokens

['studi', 'nlp', 'first', 'lectur']

In [15]:
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()
lemmitized_tokens = [lem.lemmatize(word) for word in tokens_without_punctuation]

In [16]:
lemmitized_tokens

['studying', 'nlp', 'first', 'lecture']

In [26]:
p.stem('jumping')

'jump'

In [24]:
lem.lemmatize('jumping')

'jumping'

In [30]:
lemmitized_tokens

['studying', 'nlp', 'first', 'lecture']

In [31]:
vec_tokens.toarray()[0]

array([0, 0, 0, 1], dtype=int64)

In [32]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [41]:
nltk.pos_tag(['beautiful'])

[('beautiful', 'NN')]

In [55]:
# part of speech

from nltk.corpus import wordnet

def get_pos_tag(word):
    tag = nltk.pos_tag([word])[0][1][0]
    dict_tags ={'V': wordnet.VERB, 'N':wordnet.NOUN, 'R':wordnet.ADV,'J':wordnet.ADJ}
    return dict_tags.get(tag,wordnet.NOUN)

In [56]:
tagged_tokens = [get_pos_tag(word) for word in lemmitized_tokens]

In [57]:
tagged_tokens

['v', 'n', 'r', 'n']

In [58]:
new_lemmitized_tokens = [lem.lemmatize(word, get_pos_tag(word)) for word in tokens_without_punctuation]

In [59]:
new_lemmitized_tokens

['study', 'nlp', 'first', 'lecture']

In [ ]:
#bow

from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()

vec_tokens = vec.fit_transform(lemmitized_tokens)

In [5]:
sentences = ["we are learning nlp", "this is the second class", "we are done wtih supervised learning"]

In [1]:
import nltk

In [2]:
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

In [9]:
from nltk.tokenize import word_tokenize
import string
def clean_text(sentence):
    tokens = word_tokenize(sentence)
    tokens = [word for word in tokens if word not in stopwords and word not in string.punctuation]
    tokens = ' '.join(tokens)
    return tokens

In [10]:
cleaned_sentences = [clean_text(sentence) for sentence in sentences]

In [11]:
cleaned_sentences

['learning nlp', 'second class', 'done wtih supervised learning']

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
sentence_vectors  = vec.fit_transform(cleaned_sentences)

In [14]:
sentence_vectors.toarray()

array([[0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 1]], dtype=int64)

In [ ]:
#tfidf

#tf (t, d) = freq of t in d doc/no. of terms in d

# idf(t, D) = no. of docs N/ no. of docs containing t

#tf-idf = tf*idf

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vec =  TfidfVectorizer()

sentence_vectors_tfidf = tfidf_vec.fit_transform(cleaned_sentences)

In [17]:
sentence_vectors_tfidf.toarray()


array([[0.        , 0.        , 0.60534851, 0.79596054, 0.        ,
        0.        , 0.        ],
       [0.70710678, 0.        , 0.        , 0.        , 0.70710678,
        0.        , 0.        ],
       [0.        , 0.52863461, 0.40204024, 0.        , 0.        ,
        0.52863461, 0.52863461]])

In [19]:
cleaned_sentences

['learning nlp', 'second class', 'done wtih supervised learning']

In [18]:
tfidf_vec.get_feature_names_out()

array(['class', 'done', 'learning', 'nlp', 'second', 'supervised', 'wtih'],
      dtype=object)

In [20]:
sentences

['we are learning nlp',
 'this is the second class',
 'we are done wtih supervised learning']

In [ ]:
# word2vec 2 layer nn 
#cbow -- predict current word using context
#skip gram --> predict context using current word

In [29]:
cleaned_sentences

['learning nlp', 'second class', 'done wtih supervised learning']

In [31]:
from nltk.tokenize import word_tokenize
import string
def clean_text(sentence):
    tokens = word_tokenize(sentence)
    tokens = [word for word in tokens if word not in stopwords and word not in string.punctuation]
    #tokens = ' '.join(tokens)
    return tokens

In [39]:
sentence_tokens = [word_tokenize(sentence.lower()) for sentence in cleaned_sentences]

In [42]:
sentence_tokens

[['learning', 'nlp'],
 ['second', 'class'],
 ['done', 'wtih', 'supervised', 'learning']]

In [45]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
    
model = Word2Vec(sentences= sentence_tokens, vector_size = 50, window= 5, min_count=1)

In [46]:

model.wv.index_to_key

['learning', 'supervised', 'wtih', 'done', 'class', 'second', 'nlp']

In [47]:
model.wv['learning']

array([-1.0724545e-03,  4.7286271e-04,  1.0206699e-02,  1.8018546e-02,
       -1.8605899e-02, -1.4233618e-02,  1.2917745e-02,  1.7945977e-02,
       -1.0030856e-02, -7.5267432e-03,  1.4761009e-02, -3.0669428e-03,
       -9.0732267e-03,  1.3108104e-02, -9.7203208e-03, -3.6320353e-03,
        5.7531595e-03,  1.9837476e-03, -1.6570430e-02, -1.8897636e-02,
        1.4623532e-02,  1.0140524e-02,  1.3515387e-02,  1.5257311e-03,
        1.2701781e-02, -6.8107317e-03, -1.8928028e-03,  1.1537147e-02,
       -1.5043275e-02, -7.8722071e-03, -1.5023164e-02, -1.8600845e-03,
        1.9076237e-02, -1.4638334e-02, -4.6675373e-03, -3.8754821e-03,
        1.6154874e-02, -1.1861792e-02,  9.0324880e-05, -9.5074680e-03,
       -1.9207101e-02,  1.0014586e-02, -1.7519170e-02, -8.7836506e-03,
       -7.0199967e-05, -5.9236289e-04, -1.5322480e-02,  1.9229487e-02,
        9.9641159e-03,  1.8466286e-02], dtype=float32)

In [50]:
def get_sentence_vector(sentence):
    tokens = word_tokenize(str(sentence.lower()))
    word_vectors = [model.wv[word] for word in tokens if word in model.wv.index_to_key]
    return numpy.mean(word_vectors, axis =0)
    

In [52]:
import numpy
sentence_vectors_word2vec = [get_sentence_vector(sentence) for sentence in cleaned_sentences]

In [53]:
sentence_vectors_word2vec

[array([-0.00877891,  0.00953579,  0.00490569,  0.007042  , -0.00469932,
        -0.01121213,  0.00920199,  0.01591296,  0.00105   , -0.01127417,
         0.01676285,  0.00313834, -0.00057049,  0.00031055,  0.00359982,
        -0.00396618,  0.01170177, -0.00437013, -0.01641463, -0.00262426,
         0.00898296,  0.00287175,  0.01627129,  0.01025672, -0.00342316,
        -0.00090014,  0.00521029,  0.00964103, -0.00549885, -0.0035056 ,
        -0.00683795, -0.00475068,  0.00239787, -0.00940804,  0.00159013,
         0.00688094,  0.01733659, -0.01190683, -0.00935751,  0.00501064,
        -0.00617377,  0.01017341, -0.00247724, -0.00719609,  0.0072876 ,
         0.00253409, -0.00479024,  0.00723437,  0.00185381,  0.006863  ],
       dtype=float32),
 array([ 0.00153159,  0.00043131, -0.01388643, -0.00918077, -0.00145321,
         0.00141124, -0.00552072, -0.00168117, -0.0147778 ,  0.00248816,
        -0.00034816, -0.00690315,  0.01768953,  0.00240738,  0.00024838,
         0.00335974,  0.012

In [54]:
import pandas as pd

news_df = pd.read_csv('news_dataset.csv')

In [55]:
news_df.head()

label                                               text
0  REAL  Payal has accused filmmaker Anurag Kashyap of ...
1  FAKE  A four-minute-long video of a woman criticisin...
2  FAKE  Republic Poll, a fake Twitter account imitatin...
3  REAL  Delhi teen finds place on UN green list, turns...
4  REAL  Delhi: A high-level meeting underway at reside...

In [56]:
news_df.shape

(3729, 2)

In [64]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string
stopwords = stopwords.words('english')
def preprocess(sentence):
    tokens = word_tokenize(str(sentence).lower())
    tokens = [word for word in tokens if word not in stopwords and word not in string.punctuation]
    return tokens 

In [65]:
news_df['clean_text'] = news_df['text'].apply(preprocess)

In [66]:
news_df.head()

label                                               text  \
0  REAL  Payal has accused filmmaker Anurag Kashyap of ...   
1  FAKE  A four-minute-long video of a woman criticisin...   
2  FAKE  Republic Poll, a fake Twitter account imitatin...   
3  REAL  Delhi teen finds place on UN green list, turns...   
4  REAL  Delhi: A high-level meeting underway at reside...   

                                          clean_text  
0  [payal, accused, filmmaker, anurag, kashyap, b...  
1  [four-minute-long, video, woman, criticising, ...  
2  [republic, poll, fake, twitter, account, imita...  
3  [delhi, teen, finds, place, un, green, list, t...  
4  [delhi, high-level, meeting, underway, residen...

In [68]:
from gensim.models import Word2Vec

model = Word2Vec(sentences = news_df['clean_text'], vector_size = 50, window = 5)

In [69]:
len(model.wv.index_to_key)

13475

In [70]:
model.wv['poll']

array([ 2.15160087e-01,  3.21336538e-01,  3.87219518e-01, -1.28771275e-01,
       -4.44069244e-02, -6.34654999e-01,  6.00438893e-01, -3.50640416e-02,
       -2.34462887e-01,  6.94480017e-02,  1.20690726e-01,  4.00881059e-02,
       -3.86360705e-01, -1.32265612e-01,  1.05808727e-01, -1.19828299e-01,
        1.22581162e-01,  2.96184152e-01, -1.92792654e-01, -2.94277251e-01,
        7.55381137e-02,  4.73819524e-02,  3.70985091e-01,  3.82441729e-01,
        1.82984337e-01, -6.45564124e-02, -2.58423924e-01, -2.42452119e-02,
       -7.53795132e-02, -3.38794470e-01,  2.08803162e-01, -2.44364962e-01,
       -2.38341242e-01, -2.96491027e-01, -2.28362769e-01,  3.36625817e-04,
       -2.63036847e-01,  1.71666265e-01, -2.02304889e-02, -1.99135855e-01,
        1.83768094e-01,  2.24796221e-01,  2.51994759e-01, -1.03595659e-01,
        2.81693101e-01,  2.25900114e-02, -4.59422469e-01, -1.62699908e-01,
       -5.30712083e-02,  1.06472991e-01], dtype=float32)

In [71]:
news_df.loc[0,'clean_text']

['payal',
 'accused',
 'filmmaker',
 'anurag',
 'kashyap',
 'behaving',
 'inappropriately',
 'video',
 'went',
 'viral',
 'maintained',
 'stance',
 'speaking',
 'etimes',
 'said',
 '“',
 'wanted',
 'speak',
 'long',
 'time',
 'today',
 'finally',
 'thought',
 'must',
 'get',
 'head',
 'tweeted',
 'incident',
 'sometime',
 'ago',
 'metoo',
 'movement',
 'happened',
 'many',
 'people',
 'told',
 'delete',
 'tweet',
 'else',
 'would',
 'stop',
 'getting',
 'work',
 'manager',
 'advised',
 'remove',
 'tweet',
 'complied',
 'post',
 'anurag',
 'blocked',
 'whatsapp',
 '”']

In [74]:
def get_vector(tokens):
    word_vector = [model.wv[word] for word in tokens if word in model.wv.index_to_key]
    sentence_vector = numpy.mean(word_vector, axis =0)
    return sentence_vector

    
    

In [77]:
sample_news_df = news_df[0:200]

In [78]:
sample_news_df['word2vec_vector']  = sample_news_df['clean_text'].apply(get_vector)

C:\Users\user\AppData\Local\Temp\ipykernel_18496\1904817262.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_news_df['word2vec_vector']  = sample_news_df['clean_text'].apply(get_vector)


In [81]:
sample_news_df.head()

label                                               text  \
0      1  Payal has accused filmmaker Anurag Kashyap of ...   
1     -1  A four-minute-long video of a woman criticisin...   
2     -1  Republic Poll, a fake Twitter account imitatin...   
3      1  Delhi teen finds place on UN green list, turns...   
4      1  Delhi: A high-level meeting underway at reside...   

                                          clean_text  \
0  [payal, accused, filmmaker, anurag, kashyap, b...   
1  [four-minute-long, video, woman, criticising, ...   
2  [republic, poll, fake, twitter, account, imita...   
3  [delhi, teen, finds, place, un, green, list, t...   
4  [delhi, high-level, meeting, underway, residen...   

                                     word2vec_vector  
0  [0.43928933, 0.27097186, 0.13300538, -0.935865...  
1  [-0.19309464, 0.8914795, 0.6746488, 0.1528777,...  
2  [0.2979288, 0.7908584, 0.8854035, -0.15631333,...  
3  [-0.04496358, 0.19419488, -0.18477531, -0.2292...  
4  [-0.51848423, 0.14019454, -0.3519918, -0.82751...

In [80]:
label_encoding = {'REAL':1, 'FAKE':-1}

sample_news_df['label'] = sample_news_df['label'].map(label_encoding)

C:\Users\user\AppData\Local\Temp\ipykernel_18496\3453965754.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_news_df['label'] = sample_news_df['label'].map(label_encoding)


In [82]:
x = sample_news_df['word2vec_vector']
y = sample_news_df['label']

In [83]:
x.shape

(200,)

In [84]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [86]:
x_test.shape

(60,)

In [88]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train.to_list(), y_train)

LogisticRegression()

In [89]:
y_pred = clf.predict(x_test.to_list())

In [92]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred, y_test))

1.0


In [104]:
user_text = input("enter some news to verify its authenticity: ")
clean_user_text = preprocess(user_text)
user_vector = get_vector(clean_user_text)
final_prediction = clf.predict(user_vector.reshape(1,-1))
if final_prediction[0]==-1:
    print("the entered news is fake")
else:
    print("the news is real")

the entered news is fake


In [96]:
user_vector

array([ 1.5767726 ,  0.4585576 ,  0.75611454,  0.05270781, -0.3146547 ,
       -1.0885375 ,  1.9330652 ,  0.81175894, -1.7773981 , -1.0639175 ,
        0.314969  , -0.2696809 , -0.90806824, -0.06326166,  0.28001642,
       -1.2410063 ,  1.0264688 ,  1.1544445 , -0.19873065, -1.8986737 ,
       -0.307828  , -0.5869638 ,  1.6938643 ,  1.3751187 , -2.2732751 ,
        0.91253835, -1.1411344 ,  1.0715941 ,  1.031589  , -0.72680986,
       -0.5332267 , -0.70994204, -0.9737197 , -0.7682363 , -0.9130855 ,
       -0.33617756, -2.0397074 , -0.7591959 ,  0.36878446, -0.6120846 ,
        1.7741998 ,  0.12396903,  0.29287052,  0.34505898, -0.17587379,
        0.9338138 , -0.9742284 , -1.1012169 , -2.0643594 ,  0.25534034],
      dtype=float32)

In [103]:
final_prediction

array([-1], dtype=int64)

similarity

In [107]:
model.wv.most_similar('real')

[('screen', 0.8789852857589722),
 ('grab', 0.8351165056228638),
 ('clipping', 0.782625138759613),
 ('example', 0.7778211236000061),
 ('unverified', 0.7724040746688843),
 ('actually', 0.7717491984367371),
 ('screenshots', 0.7686144113540649),
 ('graphic', 0.7637912034988403),
 ('display', 0.7634642720222473),
 ('shown', 0.7599057555198669)]

In [111]:
from transformers import pipeline

classfier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
