libraries

functions-->classes-->modules-->libraries

In [1]:
import numpy

In [6]:
list_1 = [1,2,3,4,5,6]
list_2 = [5,6,7,8,9,10]
#list_1.append()

arr_1 = numpy.array(list_1)
arr_2 = numpy.array(list_2)

In [5]:
type(list_1)

list

In [7]:
arr_1 + arr_2

array([ 6,  8, 10, 12, 14, 16])

In [8]:
list_1 + list_2

[1, 2, 3, 4, 5, 6, 5, 6, 7, 8, 9, 10]

In [13]:
list_3 = list(range(100000))
list_4 = list(range(100000))

In [12]:
type(list_3)

list

In [14]:
arr_3 = numpy.array(list_3)
arr_4 = numpy.array(list_4)

In [15]:
import sys
print("the memory taken by list3 is ", sys.getsizeof(list_3)*len(list_3))

the memory taken by list3 is  80005600000


In [18]:
arr_3.size *arr_3.itemsize

400000

In [29]:
import time

initial_time = time.time()

list_5 = [numpy.exp(2*a*b) for a, b in zip(list_3, list_4)]
print("time diff is ", time.time()-initial_time)

C:\Users\user\AppData\Local\Temp\ipykernel_14436\3480340868.py:5: RuntimeWarning: overflow encountered in exp
  list_5 = [numpy.exp(2*a*b) for a, b in zip(list_3, list_4)]


time diff is  1.6266334056854248


In [31]:
initial_time = time.time()

arr_5 = numpy.exp(2*arr_3*arr_4)
print("time diff is ", time.time()- initial_time)

time diff is  0.017002582550048828


C:\Users\user\AppData\Local\Temp\ipykernel_14436\1211779656.py:3: RuntimeWarning: overflow encountered in exp
  arr_5 = numpy.exp(2*arr_3*arr_4)


In [32]:
list_6 = [[1,2], [3,4]]

In [37]:
list_6

[[1, 2], [3, 4]]

In [35]:
list_6[1][1]

4

In [38]:
array_6 = numpy.array(list_6)

In [40]:
array_6.shape

(2, 2)

In [41]:
array_6

array([[1, 2],
       [3, 4]])

In [43]:
array_6[1,1]

4

In [1]:
import numpy as np

some_array = np.arange(2,8)

In [2]:
some_array

array([2, 3, 4, 5, 6, 7])

In [3]:
some_array.shape

(6,)

In [4]:
some_array.ndim

1

In [5]:
some_array.size

6

In [15]:
some_array.shape = (6,1)

In [16]:
some_array

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [17]:
some_array = np.reshape(some_array, (2,3))

In [19]:
some_array

array([[2, 3, 4],
       [5, 6, 7]])

In [24]:
some_array.shape[1]

3

In [25]:
for i in range(some_array.shape[0]):
    for j in range(some_array.shape[1]):
        print(f"the value at row {i} and column {j} is {some_array[i,j]}")

the value at row 0 and column 0 is 2
the value at row 0 and column 1 is 3
the value at row 0 and column 2 is 4
the value at row 1 and column 0 is 5
the value at row 1 and column 1 is 6
the value at row 1 and column 2 is 7


In [28]:
some_other_array = np.linspace(10,20,10)

In [29]:
some_other_array

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [30]:
some_array

array([[2, 3, 4],
       [5, 6, 7]])

In [31]:
np.resize(some_array,(2,5))

array([[2, 3, 4, 5, 6],
       [7, 2, 3, 4, 5]])

In [32]:
some_random_array = np.random.random(10)

In [33]:
some_random_array

array([0.16186616, 0.10068531, 0.83614018, 0.96184401, 0.37158524,
       0.58457845, 0.51899534, 0.24306192, 0.90622341, 0.05902979])

In [37]:
rand_int_array = np.random.randint(2,9,size= (4,4))

In [39]:
rand_int_array.shape = (8,2)

In [40]:
rand_int_array

array([[2, 5],
       [7, 2],
       [7, 4],
       [7, 5],
       [4, 7],
       [7, 3],
       [5, 7],
       [2, 2]])

In [42]:
rand_int_array.transpose()

array([[2, 7, 7, 7, 4, 7, 5, 2],
       [5, 2, 4, 5, 7, 3, 7, 2]])

In [43]:
np.empty(10)

array([0.16186616, 0.10068531, 0.83614018, 0.96184401, 0.37158524,
       0.58457845, 0.51899534, 0.24306192, 0.90622341, 0.05902979])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [58]:
some_3d_array = np.random.randint(1,9,size=(3,3,3))

In [47]:
some_3d_array

array([[[7, 1, 4],
        [7, 2, 7],
        [4, 7, 8]],

       [[8, 1, 4],
        [4, 8, 4],
        [2, 3, 2]],

       [[3, 8, 8],
        [7, 7, 5],
        [5, 5, 7]]])

In [54]:
some_3d_array[0:3,1,:]

array([[7, 2, 7],
       [4, 8, 4],
       [7, 7, 5]])

In [56]:
some_3d_array.sort()

In [59]:
some_3d_array

array([[[1, 1, 5],
        [6, 1, 2],
        [6, 7, 1]],

       [[4, 1, 1],
        [8, 8, 3],
        [5, 1, 5]],

       [[1, 2, 7],
        [2, 8, 8],
        [2, 3, 6]]])

In [63]:
some_other_array.shape =(5,2)

In [64]:
some_other_array

array([[10.        , 11.11111111],
       [12.22222222, 13.33333333],
       [14.44444444, 15.55555556],
       [16.66666667, 17.77777778],
       [18.88888889, 20.        ]])

In [68]:
some_random_array

array([0.16186616, 0.10068531, 0.83614018, 0.96184401, 0.37158524,
       0.58457845, 0.51899534, 0.24306192, 0.90622341, 0.05902979])

In [69]:
np.sort(some_random_array)

array([0.05902979, 0.10068531, 0.16186616, 0.24306192, 0.37158524,
       0.51899534, 0.58457845, 0.83614018, 0.90622341, 0.96184401])

In [70]:
arr1 = np.random.randint(2,9,(3,3))

In [71]:
arr1

array([[7, 8, 5],
       [8, 7, 2],
       [5, 2, 7]])

In [74]:
np.sort(arr1, axis =0)

array([[5, 2, 2],
       [7, 7, 5],
       [8, 8, 7]])

In [76]:
np.sort(arr1)

TypeError: sort() got an unexpected keyword argument 'ascending'

In [79]:
arr1.ndim

2

In [80]:
arr1

array([[7, 8, 5],
       [8, 7, 2],
       [5, 2, 7]])

In [81]:
arr1.flatten(order='F')

array([7, 8, 5, 8, 7, 2, 5, 2, 7])

In [84]:
np.min(arr1, axis=0)

array([5, 2, 2])

In [86]:
np.mean(arr1, axis =1)

array([6.66666667, 5.66666667, 4.66666667])

In [88]:
np.sum(arr1, axis =0)

array([20, 17, 14])

In [95]:
list1 =[1,2,3,4]

list2 = list1.copy()


list2[2]= 30

In [96]:
list2

[1, 2, 30, 4]

In [97]:
list1

[1, 2, 30, 4]