In [1]:
list1 = [1,2,3,45,"something"]
list1.append("something else")

In [2]:
list1

[1, 2, 3, 45, 'something', 'something else']

In [5]:
list_1 = [1,2,3,4,5]
list_2 =[6,7,8,9,9]

list_3 =[]

for i in range(len(list_1)):
    list_3.append(list_1[i]+list_2[i])

In [6]:
list_3

[7, 9, 11, 13, 14]

In [7]:
import numpy
arr_1 = numpy.array(list_1)
arr_2 = numpy.array(list_2)

In [8]:
arr_3 = arr_1 + arr_2

In [9]:
arr_3

array([ 7,  9, 11, 13, 14])

In [1]:
import time

list_1 = list(range(10000000))
list_2 = list(range(10000000))

In [6]:
import numpy
arr_1 = numpy.array(list_1)
arr_2 = numpy.array(list_2)

In [3]:
import time

initial_time = time.time()

list_3 = [a*b for a, b in zip(list_1, list_2)]

print("time taken by list op is ", initial_time- time.time())

time taken by list op is  -3.232863664627075


In [8]:
initial_time = time.time()

arr_3 = arr_1 * arr_2

print("time taken by arr op is ", time.time()- initial_time)

time taken by arr op is  0.18200182914733887


In [10]:
import sys

sys.getsizeof(list_1)* len(list_1)

800000560000000

In [12]:
arr_1.size * arr_1.itemsize

40000000

In [13]:
arr_1.shape

(10000000,)

In [14]:
arr_1.ndim

1

In [19]:
arr_4 = numpy.array([1,2,3,4,5,6])

In [18]:
arr_4.shape

(6,)

In [20]:
arr_4

array([1, 2, 3, 4, 5, 6])

In [21]:
arr_4.shape = (2,3)

In [22]:
arr_4

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr_4[1,0:2]

array([4, 5])