In [1]:
list1 = [1,2,3,45,"something"]
list1.append("something else")

In [2]:
list1

[1, 2, 3, 45, 'something', 'something else']

In [5]:
list_1 = [1,2,3,4,5]
list_2 =[6,7,8,9,9]

list_3 =[]

for i in range(len(list_1)):
    list_3.append(list_1[i]+list_2[i])

In [6]:
list_3

[7, 9, 11, 13, 14]

In [7]:
import numpy
arr_1 = numpy.array(list_1)
arr_2 = numpy.array(list_2)

In [8]:
arr_3 = arr_1 + arr_2

In [9]:
arr_3

array([ 7,  9, 11, 13, 14])

In [1]:
import time

list_1 = list(range(10000000))
list_2 = list(range(10000000))

In [6]:
import numpy
arr_1 = numpy.array(list_1)
arr_2 = numpy.array(list_2)

In [3]:
import time

initial_time = time.time()

list_3 = [a*b for a, b in zip(list_1, list_2)]

print("time taken by list op is ", initial_time- time.time())

time taken by list op is  -3.232863664627075


In [8]:
initial_time = time.time()

arr_3 = arr_1 * arr_2

print("time taken by arr op is ", time.time()- initial_time)

time taken by arr op is  0.18200182914733887


In [10]:
import sys

sys.getsizeof(list_1)* len(list_1)

800000560000000

In [12]:
arr_1.size * arr_1.itemsize

40000000

In [13]:
arr_1.shape

(10000000,)

In [14]:
arr_1.ndim

1

In [19]:
arr_4 = numpy.array([1,2,3,4,5,6])

In [18]:
arr_4.shape

(6,)

In [20]:
arr_4

array([1, 2, 3, 4, 5, 6])

In [21]:
arr_4.shape = (2,3)

In [22]:
arr_4

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr_4[1,0:2]

array([4, 5])

In [36]:
import numpy as np

arr_2d = np.array([[1,2,3,9],[4,5,6,9]])

In [37]:
arr_2d

array([[1, 2, 3, 9],
       [4, 5, 6, 9]])

In [29]:
arr_2d.shape

(2, 3)

In [30]:
arr_2d.size

6

In [31]:
arr_2d[0,0]

1

In [39]:
arr_2d.shape

(2, 4)

In [41]:
arr_2d

array([[1, 2, 3, 9],
       [4, 5, 6, 9]])

In [43]:
for i in range(arr_2d.shape[0]):
    for j in range(arr_2d.shape[1]):
        print(f"the element at index {i}, {j} is: {arr_2d[i,j]}")
        

the element at index 0, 0 is: 1
the element at index 0, 1 is: 2
the element at index 0, 2 is: 3
the element at index 0, 3 is: 9
the element at index 1, 0 is: 4
the element at index 1, 1 is: 5
the element at index 1, 2 is: 6
the element at index 1, 3 is: 9


In [46]:
arr_3d = np.arange(27)

In [48]:
arr_3d.size

27

In [51]:
arr_3d.shape = (3,3,3)

In [52]:
arr_3d.shape

(3, 3, 3)

In [53]:
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
arr_3d[2,:,2]

array([20, 23, 26])

In [58]:
arr_3d[1,0:2,:]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [59]:
arr_3d[0:2,0,:]

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [54]:
arr_3d.ndim

3

In [55]:
arr_3d.dtype

dtype('int32')

In [62]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([2,3,4,5,6])

In [63]:
arr_1 + arr_2

array([ 3,  5,  7,  9, 11])

In [64]:
print("tje squre root of arr_1 is ", np.sqrt(arr_1))

tje squre root of arr_1 is  [1.         1.41421356 1.73205081 2.         2.23606798]


In [65]:
print("the sum of elements of arr_2 is ", np.sum(arr_2))

the sum of elements of arr_2 is  20


In [66]:
for i, element in enumerate(arr_1):
    print(f"the element at index {i} is {element}")

the element at index 0 is 1
the element at index 1 is 2
the element at index 2 is 3
the element at index 3 is 4
the element at index 4 is 5


In [67]:
for element in arr_2:
    print(element)

2
3
4
5
6


In [71]:
print("the mean of arr_1 is ", int(np.mean(arr_1)))

the mean of arr_1 is  3


In [72]:
print("the minimum value of arr1 is ", np.min(arr1))

the minimum value of arr1 is  1


In [73]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [74]:
a

array([[1, 2],
       [3, 4]])

In [75]:
b

array([[5, 6],
       [7, 8]])

In [77]:
c = np.dot(a,b)
print("the dot product if a and b matrices is ", c)


the dot product if a and b matrices is  [[19 22]
 [43 50]]


In [79]:
print("the detemitant of a matrix is ", np.linalg.det(c))

the detemitant of a matrix is  4.000000000000008


In [82]:
print("the eigen values and vectors of arr1 are", np.linalg.eig(a))

the eigen values and vectors of arr1 are EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [83]:
ones_arr = np.ones(10)

In [85]:
ones_arr = np.reshape(ones_arr,(2,5))
#ones_arr.shape =(2,5)

In [86]:
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [91]:
random_arr = np.random.random(100)

In [92]:
random_arr.shape

(100,)

In [97]:
#random_arr2 = np.random.randint(100)

In [104]:
random_arr2 = np.random.rand(4,3,3)

In [108]:
random_arr3 = np.random.randint(4,10, size=(3,3))

In [109]:
random_arr3

array([[7, 5, 8],
       [4, 9, 9],
       [5, 7, 8]])

In [111]:
# in agg funs 0 means cols and 1 means rows
np.sort(random_arr3, axis =0)

array([[4, 5, 8],
       [5, 7, 8],
       [7, 9, 9]])

In [8]:
import numpy as np
some_arr_3 = np.random.randint(3,9,(3,4,4))

In [19]:
some_arr_3

array([[[7, 5, 8, 5],
        [8, 4, 6, 5],
        [3, 7, 8, 5],
        [8, 8, 6, 4]],

       [[8, 6, 7, 8],
        [8, 4, 4, 7],
        [8, 6, 7, 5],
        [4, 3, 8, 7]],

       [[8, 6, 4, 3],
        [7, 8, 7, 4],
        [6, 6, 6, 8],
        [4, 6, 4, 8]]])

In [3]:
some_arr_3.ndim

3

In [5]:
some_arr_3[0,2,2]

3

In [10]:
some_arr_2 = np.random.randint(4,10, (5,5))

In [32]:
some_arr_2

array([[8, 7, 9, 4, 8],
       [8, 9, 4, 7, 7],
       [6, 4, 5, 5, 4],
       [4, 8, 6, 6, 4],
       [8, 8, 6, 6, 7]])

In [13]:
some_arr_2.shape

(5, 5)

In [18]:
np.insert(some_arr_2 ,2, 0, axis=1)

array([[8, 7, 0, 9, 4, 8],
       [8, 9, 0, 4, 7, 7],
       [6, 4, 0, 5, 5, 4],
       [4, 8, 0, 6, 6, 4],
       [8, 8, 0, 6, 6, 7]])

In [ ]:
some_arr_2[,]

In [20]:
some_arr_3

array([[[7, 5, 8, 5],
        [8, 4, 6, 5],
        [3, 7, 8, 5],
        [8, 8, 6, 4]],

       [[8, 6, 7, 8],
        [8, 4, 4, 7],
        [8, 6, 7, 5],
        [4, 3, 8, 7]],

       [[8, 6, 4, 3],
        [7, 8, 7, 4],
        [6, 6, 6, 8],
        [4, 6, 4, 8]]])

In [33]:
some_arr_3[2,2,3]

8

In [ ]:
some_arr_3[2,:,:]

In [21]:
some_arr_3 = np.insert(some_arr_3, 2, 9, axis=0)

array([[[7, 5, 8, 5],
        [8, 4, 6, 5],
        [3, 7, 8, 5],
        [8, 8, 6, 4]],

       [[8, 6, 7, 8],
        [8, 4, 4, 7],
        [8, 6, 7, 5],
        [4, 3, 8, 7]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[8, 6, 4, 3],
        [7, 8, 7, 4],
        [6, 6, 6, 8],
        [4, 6, 4, 8]]])

In [22]:
some_arr_1 = np.arange(10)

In [27]:
some_arr_1.shape = (2,5)

In [ ]:
some_arr_1 + 10

In [30]:
some_arr_1.shape

(2, 5)

In [29]:
some_arr_1 + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
some_arr_3

array([[[7, 5, 8, 5],
        [8, 4, 6, 5],
        [3, 7, 8, 5],
        [8, 8, 6, 4]],

       [[8, 6, 7, 8],
        [8, 4, 4, 7],
        [8, 6, 7, 5],
        [4, 3, 8, 7]],

       [[8, 6, 4, 3],
        [7, 8, 7, 4],
        [6, 6, 6, 8],
        [4, 6, 4, 8]]])

In [36]:
np.insert(some_arr_3, 2, 9, axis = 0)

array([[[7, 5, 8, 5],
        [8, 4, 6, 5],
        [3, 7, 8, 5],
        [8, 8, 6, 4]],

       [[8, 6, 7, 8],
        [8, 4, 4, 7],
        [8, 6, 7, 5],
        [4, 3, 8, 7]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[8, 6, 4, 3],
        [7, 8, 7, 4],
        [6, 6, 6, 8],
        [4, 6, 4, 8]]])

In [37]:
some_arr_2

array([[8, 7, 9, 4, 8],
       [8, 9, 4, 7, 7],
       [6, 4, 5, 5, 4],
       [4, 8, 6, 6, 4],
       [8, 8, 6, 6, 7]])

In [38]:
np.insert(some_arr_2, 3, 0, axis =1)

array([[8, 7, 9, 0, 4, 8],
       [8, 9, 4, 0, 7, 7],
       [6, 4, 5, 0, 5, 4],
       [4, 8, 6, 0, 6, 4],
       [8, 8, 6, 0, 6, 7]])

In [50]:
a = [4,4,4,4,4]

a = np.array(a)

a.shape =(5,1)

In [42]:
some_arr_2[:,3].shape

(5,)

In [58]:
a

array([[4],
       [4],
       [4],
       [4],
       [4]])

In [51]:
np.append(some_arr_2,a, axis=1)

array([[8, 7, 9, 4, 8, 4],
       [8, 9, 4, 7, 7, 4],
       [6, 4, 5, 5, 4, 4],
       [4, 8, 6, 6, 4, 4],
       [8, 8, 6, 6, 7, 4]])

In [54]:
b = [5,6,7,8,9]

b = np.array(b)
b.shape = (1,5)

In [55]:
b

array([[5, 6, 7, 8, 9]])

In [ ]:
# 3d array

# 0 axis means arry/matrix number, 1 axis means rows and 2 axis means cols



In [57]:
np.append(some_arr_2, [[5,6,7,8,9]], axis= 0)

array([[8, 7, 9, 4, 8],
       [8, 9, 4, 7, 7],
       [6, 4, 5, 5, 4],
       [4, 8, 6, 6, 4],
       [8, 8, 6, 6, 7],
       [5, 6, 7, 8, 9]])